# Base image
FROM python:3.11-slim-bullseye

# Working directory
WORKDIR /app

# requirements.txt copy karke dependencies install karo
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Baqi saara project code copy karo
COPY . .

# Port 8501 expose karo Streamlit UI ke liye
EXPOSE 8501

# Streamlit UI ko start karne ki command
CMD ["streamlit", "run", "ui/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
